language: cpp
dist: trusty
sudo: false
cache: ccache
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libboost-dev
    - libboost-system-dev
env:
  global:
  - ENV_EVAL="CXX=g++-7 CC=gcc-7"
  - MAKEFLAGS="-j 3"
  matrix:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebInfo
  - BUILD_TYPE=MinSizeRel
  - BUILD_TYPE=Release
before_install:
- eval "${ENV_EVAL}"
- travis_retry curl https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz > cmake.tar.gz
- tar xf cmake.tar.gz
- export PATH=${HOME}/cmake-3.10.0-Linux-x86_64/cmake/bin:${PATH}
before_script:
- mkdir build
- cd build
script:
- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
- make $MAKEFLAGS
- ctest
after_failure:
- cat Testing/Temporary/LastTest.log
